spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: question-service
          uri: http://localhost:8081
          predicates:
            - Path=/questions/**
        - id: quiz-service
          uri: http://localhost:8082
          predicates:
            - Path=/quiz/**

      # ✅ Add global CORS configuration
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
